### ISSUE TITLE
Transfer Ownership on PyPI Server

### ISSUE THREAD

**Issue by dhilipsiva** [iOSForensics/pymobiledevice#12]
Hey Guys,

I am currently owner of this package on PyPI (https://pypi.python.org/pypi/pymobiledevice) - do you guys want me to transfer this ownership to you? It rightfully belongs to you. If you guys are interested, please reply with your PyPI server `username`.

**Comment by dhilipsiva** [comment]
@GotoHack ?

**Comment by GotoHack** [comment]
username: gotohack thank you.

**Comment by dhilipsiva** [comment]
@GotoHack I added you as the owner for the package: https://pypi.python.org/pypi/pymobiledevice You can remove me as an owner if you want to. You can use this link to edit roles after logging in on PyPI: https://pypi.python.org/pypi?:action=role_form&package_name=pymobiledevice
