### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by jpstotz** [iOSForensics/pymobiledevice#24]
In several files pymobiledevice uses a python module `util` which is not available in Python3.
It is also not mentioned in the [requirements.txt](https://github.com/iOSForensics/pymobiledevice/blob/master/requirements.txt) file.

**Comment by tech234a** [comment]
The `util` module seems to be included with the `pymobiledevice` module itself, however, I am also having errors with it. I suspect it has to do with there being no builds of a Python 3 compatible version of the `m2cryptowin64` module, as successfully installing that in Python 2.7 solved this error in Python 2.7.

**Comment by tech234a** [comment]
Update: I found that changing all instances of `from util` to `from pymobiledevice.util` or `import util` to `import pymobiledevice.util` solved this problem on Python 3.8.1.
