### ISSUE TITLE
Already paired device fails to vailidate_pair

### ISSUE THREAD

**Issue by jhihn** [iOSForensics/pymobiledevice#34]
I am running usbmuxd from libimobiledevice proper. I have paired the device using idevicepair.

It seems that this line in lockdown.py:

        self.udid = self.allValues.get("UniqueDeviceID").replace('-','')

if breaking compatibility with that library as libimobiledevice stores the filename with the `-` in it. Removing `.replace('-','')` restored compatibility

**Comment by GotoHack** [comment]
Fixed by d1d7b42
